version: 1.0.2.{build}
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: nuget pack BigBlueButtonApi\BigBlueButtonApi.csproj -OutputDirectory BigBlueButtonApi
artifacts:
- path: /BigBlueButtonApi\**\*.nupkg/
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: UIcuz+2JcyyRodz5P91RvIw1ddBj4ifRrKE+Il7jc5MqOG3zCQjLwtZ6Qnchk+VK
  skip_symbols: true
  on:
    branch: master
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'