version: 1.0.0.{build}
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: /*.nupkg/
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: UIcuz+2JcyyRodz5P91RvIw1ddBj4ifRrKE+Il7jc5MqOG3zCQjLwtZ6Qnchk+VK
  skip_symbols: true
  on:
    branch: master